version: '2'
services:
  nats-main:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
  nats-2:
    image: nats
    links:
      - nats-main
    # ports:
    #   - 4222:4222
    #   - 6222:6222
    #   - 8222:8222
    command: >
      -c nats-server.conf 
      --routes=nats-route://ruser:T0pS3cr3t@nats-main:6222 
      -DV
  nats-3:
    image: nats
    links:
      - nats-main
    # ports:
    #   - 4222:4222
    #   - 6222:6222
    #   - 8222:8222
    command: >
      -c nats-server.conf 
      --routes=nats-route://ruser:T0pS3cr3t@nats-main:6222 
      -DV